name: Deploy a new version

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: dev-cd
    
    permissions:
      id-token: write

    steps:
      #
      # Login to Azure.
      #
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #
      # Update Container App
      #
      - name: Update Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n mil-d-init-ca -g mil-d-app-rg --image ghcr.io/pagopa/mil-functions:1.0.40
