name: Pull request title validation for semantic versioning

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-validation:
    name: Validate PR title
    runs-on: ubuntu-latest
    
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            docs
            refactor
            fix
            feat
            breaking
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            doesn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: false